import { Resend } from 'resend';
import { DigestContent, DigestItem } from '@/types';

// Lazy initialization to avoid build-time errors
let _resend: Resend | null = null;

function getResendClient(): Resend {
  if (!_resend) {
    _resend = new Resend(process.env.RESEND_API_KEY);
  }
  return _resend;
}

function formatDigestItem(item: DigestItem): string {
  return `
    <tr>
      <td style="padding: 12px 0; border-bottom: 1px solid #eee;">
        <a href="${item.url}" style="color: #1a1a1a; text-decoration: none; font-weight: 600; font-size: 15px;">
          ${item.title}
        </a>
        <p style="margin: 4px 0 0 0; color: #666; font-size: 13px; line-height: 1.4;">
          ${item.summary}
        </p>
        <p style="margin: 4px 0 0 0; color: #0066cc; font-size: 12px;">
          ${item.why_it_matters}
        </p>
        <p style="margin: 4px 0 0 0;">
          ${item.topics.map(t => `<span style="background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 11px; margin-right: 4px;">${t}</span>`).join('')}
        </p>
      </td>
    </tr>
  `;
}

function formatSection(title: string, emoji: string, items: DigestItem[]): string {
  if (items.length === 0) return '';

  return `
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom: 24px;">
      <tr>
        <td style="padding-bottom: 8px; border-bottom: 2px solid #1a1a1a;">
          <h2 style="margin: 0; font-size: 18px; color: #1a1a1a;">
            ${emoji} ${title}
          </h2>
        </td>
      </tr>
      ${items.map(formatDigestItem).join('')}
    </table>
  `;
}

export function generateDigestHtml(date: string, content: DigestContent): string {
  const formattedDate = new Date(date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #fff;">
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td style="padding-bottom: 20px; border-bottom: 3px solid #1a1a1a;">
            <h1 style="margin: 0; font-size: 24px; color: #1a1a1a;">
              AI News Digest
            </h1>
            <p style="margin: 4px 0 0 0; color: #666; font-size: 14px;">
              ${formattedDate}
            </p>
          </td>
        </tr>
        <tr>
          <td style="padding-top: 20px;">
            ${formatSection('Must Know', '🔴', content.must_know)}
            ${formatSection('Worth a Look', '🟡', content.worth_a_look)}
            ${formatSection('Quick Hits', '🔵', content.quick_hits)}
          </td>
        </tr>
        <tr>
          <td style="padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px;">
            <p>
              Generated by AI News Agent •
              <a href="${process.env.NEXT_PUBLIC_VERCEL_URL || 'http://localhost:3000'}" style="color: #666;">
                View on Dashboard
              </a>
            </p>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
}

export function generateDigestText(date: string, content: DigestContent): string {
  const lines: string[] = [];
  const formattedDate = new Date(date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  lines.push(`AI News Digest - ${formattedDate}`);
  lines.push('='.repeat(50));
  lines.push('');

  if (content.must_know.length > 0) {
    lines.push('🔴 MUST KNOW');
    lines.push('-'.repeat(20));
    content.must_know.forEach((item) => {
      lines.push(`• ${item.title}`);
      lines.push(`  ${item.summary}`);
      lines.push(`  → ${item.why_it_matters}`);
      lines.push(`  ${item.url}`);
      lines.push('');
    });
  }

  if (content.worth_a_look.length > 0) {
    lines.push('🟡 WORTH A LOOK');
    lines.push('-'.repeat(20));
    content.worth_a_look.forEach((item) => {
      lines.push(`• ${item.title}`);
      lines.push(`  ${item.summary}`);
      lines.push(`  ${item.url}`);
      lines.push('');
    });
  }

  if (content.quick_hits.length > 0) {
    lines.push('🔵 QUICK HITS');
    lines.push('-'.repeat(20));
    content.quick_hits.forEach((item) => {
      lines.push(`• ${item.title} — ${item.url}`);
    });
  }

  return lines.join('\n');
}

export async function sendDigestEmail(
  date: string,
  content: DigestContent
): Promise<{ success: boolean; error?: string }> {
  const to = process.env.DIGEST_EMAIL_TO;
  const from = process.env.DIGEST_EMAIL_FROM || 'AI News Agent <onboarding@resend.dev>';

  if (!to) {
    return { success: false, error: 'DIGEST_EMAIL_TO not configured' };
  }

  try {
    const resend = getResendClient();
    const { error } = await resend.emails.send({
      from,
      to: [to],
      subject: `AI News Digest — ${new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`,
      html: generateDigestHtml(date, content),
      text: generateDigestText(date, content),
    });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}
